apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rn3t72jd2-nodejs 
  janus-idp.io/tekton: rn3t72jd2-nodejs
  backstage.io/kubernetes-id: rn3t72jd2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rn3t72jd2-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml