apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rn3t72jd2-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rn3t72jd2-nodejs 
  name: rn3t72jd2-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rn3t72jd2-nodejs 
